export default {
  login: "PratapTyagi",
  id: 45279411,
  node_id: "MDQ6VXNlcjQ1Mjc5NDEx",
  avatar_url: "https://avatars0.githubusercontent.com/u/45279411?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/PratapTyagi",
  html_url: "https://github.com/PratapTyagi",
  followers_url: "https://api.github.com/users/PratapTyagi/followers",
  following_url:
    "https://api.github.com/users/PratapTyagi/following{/other_user}",
  gists_url: "https://api.github.com/users/PratapTyagi/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/PratapTyagi/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/PratapTyagi/subscriptions",
  organizations_url: "https://api.github.com/users/PratapTyagi/orgs",
  repos_url: "https://api.github.com/users/PratapTyagi/repos",
  events_url: "https://api.github.com/users/PratapTyagi/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/PratapTyagi/received_events",
  type: "User",
  site_admin: false,
  name: "Pratap Tyagi",
  company: null,
  blog: "",
  location: null,
  email: null,
  hireable: null,
  bio: "I  am a passionate web designer and developer.\r\nStack:- MERN\r\n",
  twitter_username: null,
  public_repos: 4,
  public_gists: 0,
  followers: 2,
  following: 3,
  created_at: "2018-11-23T04:35:03Z",
  updated_at: "2020-11-26T20:38:56Z",
};
